from django.db import models


class QANote(models.Model):
    QUESTION_TYPE_CHOICES = [
        ('dsa', 'DSA'),
        ('system_design', 'System Design'),
        ('os', 'Operating System'),
        ('dbms', 'DBMS'),
        ('networking', 'Networking'),
        ('oop', 'OOP'),
        ('sql', 'SQL'),
        ('javascript', 'JavaScript'),
        ('python', 'Python'),
        ('react', 'React'),
        ('behavioral', 'Behavioral'),
        ('other', 'Other'),
        ('aws', 'AWS'),
        ('django', 'Django'),
        ('linux','Linux'),
        ('docker','Docker')
    ]

    QUESTION_FORMAT_CHOICES = [
        ('multiple_choice', 'Multiple Choice'),
        ('description', 'Description Based'),
    ]

    # Hierarchical subtopics for each question type
    QUESTION_SUBTOPICS = {
        'dsa': [
            'Arrays (prefix sum, sliding window)',
            'Strings (pattern matching, anagrams)',
            'Linked List (reverse, cycle detection)',
            'Stack & Queue (monotonic stack, LRU)',
            'Recursion & Backtracking',
            'Sorting (merge, quick, heap)',
            'Searching (binary search variations)',
            'Hashing (hash map, set)',
            'Trees (BST, traversal, LCA)',
            'Heap / Priority Queue',
            'Graphs (BFS, DFS, Dijkstra, Union-Find)',
            'Dynamic Programming (knapsack, LIS)',
            'Greedy Algorithms',
            'Bit Manipulation',
        ],
        'system_design': [
            'HLD (High Level Design)',
            'LLD (Low Level Design)',
            'Scalability (horizontal vs vertical)',
            'Load Balancing',
            'Caching (Redis)',
            'Database Sharding & Partitioning',
            'CAP Theorem',
            'Microservices Architecture',
            'API Gateway',
            'Rate Limiting',
            'Message Queues (Kafka, RabbitMQ)',
            'Circuit Breaker Pattern',
            'Retry Mechanism',
            'Saga Pattern',
            'CDN (CloudFront)',
            'Logging & Monitoring',
            'Authentication & Authorization (JWT, OAuth)',
            'Consistency (strong vs eventual)',
        ],
        'os': [
            'Process vs Thread',
            'Scheduling Algorithms',
            'Context Switching',
            'Deadlocks',
            'Memory Management',
            'Paging & Segmentation',
            'Virtual Memory',
            'File System',
            'System Calls',
            'Inter-Process Communication (IPC)',
            'Multithreading vs Multiprocessing',
        ],
        'dbms': [
            'Database Basics',
            'ACID Properties',
            'Normalization',
            'Indexing (B-Tree, Hash)',
            'Transactions',
            'Locks (shared/exclusive)',
            'Isolation Levels',
            'Deadlock Handling',
            'Query Optimization',
            'ER Diagram',
            'Joins (inner, outer)',
            'NoSQL vs SQL',
        ],
        'networking': [
            'OSI Model',
            'TCP vs UDP',
            'HTTP vs HTTPS',
            'REST API principles',
            'DNS',
            'IP Addressing',
            'Load Balancing',
            'SSL/TLS',
            'WebSockets',
            'CDN',
        ],
        'oop': [
            'Classes & Objects',
            'Encapsulation',
            'Abstraction',
            'Inheritance (types)',
            'Polymorphism',
            'Method Overloading/Overriding',
            'SOLID Principles',
            'Design Patterns (Factory, Singleton)',
            'MRO (Method Resolution Order)',
        ],
        'sql': [
            'CRUD Operations',
            'Joins (all types)',
            'Subqueries',
            'Indexes',
            'Group By & Aggregation',
            'Window Functions',
            'Transactions',
            'Stored Procedures',
            'Query Optimization',
            'N+1 Problem',
        ],
        'javascript': [
            'Variables (var, let, const)',
            'Closures',
            'Promises',
            'Async/Await',
            'Event Loop',
            'Hoisting',
            'DOM Manipulation',
            'ES6 Features',
            'Fetch API / Axios',
        ],
        'python': [
            'Data Types',
            'OOP in Python',
            'Decorators',
            'Generators & Iterators',
            'GIL (Global Interpreter Lock)',
            'Multithreading vs Multiprocessing',
            'Asyncio',
            'Memory Management',
            'Lambda Functions',
            'Exception Handling',
            'File Handling',
        ],
        'react': [
            'Components (Functional/Class)',
            'Hooks (useState, useEffect)',
            'Props & State',
            'Context API',
            'Redux Toolkit',
            'Routing (React Router)',
            'Forms Handling',
            'API Integration',
            'Performance Optimization',
        ],
        'behavioral': [
            'Tell me about yourself',
            'Strengths & Weaknesses',
            'Conflict handling',
            'Leadership experience',
            'Failure story',
            'Teamwork',
            'Time management',
            'Why should we hire you',
            'Career goals',
        ],
        'aws': [
            'EC2 (Compute)',
            'S3 (Storage)',
            'RDS (Database)',
            'IAM (Roles & Policies)',
            'VPC (Networking)',
            'Load Balancer (ALB/NLB)',
            'Auto Scaling',
            'CloudWatch',
            'SNS / SQS',
            'Lambda',
            'API Gateway',
            'CloudFront',
            'DynamoDB',
            'Elastic Beanstalk',
        ],
        'django': [
            'Project Structure',
            'Models & ORM',
            'Views & URLs',
            'Templates',
            'Middleware',
            'Authentication',
            'Django REST Framework (DRF)',
            'Serializers',
            'Pagination',
            'Signals',
            'Caching',
            'Celery Integration',
            'Deployment (Gunicorn + Nginx)',
        ],
        'linux': [
            'Basic Commands',
            'File Permissions',
            'Process Management',
            'Networking Commands',
            'Package Management',
            'Shell Scripting',
            'Cron Jobs',
            'Logs (journalctl)',
            'SSH',
            'Disk Management',
        ],
        'docker': [
            'Docker Basics',
            'Dockerfile',
            'Docker Compose',
            'Volumes',
            'Networking',
            'Image vs Container',
            'Multi-stage Builds',
            'Docker Registry',
            'Container Orchestration Basics',
        ],
        'other': [],
    }

    question = models.TextField()
    answer = models.TextField(blank=True)
    question_type = models.CharField(
        max_length=50,
        choices=QUESTION_TYPE_CHOICES,
        default='other'
    )
    question_subtopic = models.CharField(
        max_length=100,
        blank=True,
        default=''
    )
    question_format = models.CharField(
        max_length=20,
        choices=QUESTION_FORMAT_CHOICES,
        default='description'
    )
    attachment = models.FileField(upload_to='notes/', blank=True, null=True)
    read_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['read_count', '-created_at']

    def __str__(self):
        return f"[{self.get_question_type_display()}] {self.question[:80]}"
